version: '3'

services:
  ewallet:
    build: .
    hostname: ewallet
    ports:
      - "9445:9445"
    environment:
      - ENV_FILE=./config/docker.env
    networks:
      - common_network
    depends_on:
      postgres-database:
        condition: service_healthy

  postgres-database:
    image: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    restart: always
    user: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - common_network

networks:
  common_network:
    name: common_network

